apps:
  - name: app-1
    script: ./app-1/index.js
    exec_mode: cluster
    instances: 2
  - name: app-2
    script: ./app-2/index.js
    exec_mode: cluster
    instances: 2
# apps:
#   - name: app
#     script: ./index.js
#     exec_mode: cluster
#     instances: max
#     watch: true
#     max_memory_restart: 10M
#     env_prod:
#       ENVIRONMENT: PRODUCTION
#     env_homolog:
#       ENVIRONMENT: HOMOLOG  